{% set version = "2.4" %}
{% set variant = "openblas" %}

package:
  name: gsl
  version: {{ version }}

source:
  url: http://ftpmirror.gnu.org/gsl/gsl-{{ version }}.tar.gz
  sha256: 4d46d07b946e7b31c19bbf33dda6204d7bedc2f5462a1bae1d4013426cd1ce9b
  patches:
  # diff from source distribution to https://github.com/ampl/gsl/
  - patch_cmake_for_windows.diff  # [win]

build:
  number: 0
  skip: True  # [win and py35]
  features:
    - vc9    # [win and py27]
    - vc14   # [win and (py35 or py36)]
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - python  # [win]
    - vc 9    # [win and py27]
    - vc 14   # [win and (py35 or py36)]
    - blas 1.1 {{ variant }}    # [not win]
    - openblas 0.2.20|0.2.20.*  # [not win]
  run:
    - vc 9    # [win and py27]
    - vc 14   # [win and (py35 or py36)]
    - blas 1.1 {{ variant }}    # [not win]
    - openblas 0.2.20|0.2.20.*  # [not win]

test:
  commands:
    - gsl-config --prefix  # [not win]
    - if not exist %LIBRARY_LIB%\\gsl.lib       exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\gslcblas.lib  exit 1   # [win]
    - if not exist %LIBRARY_BIN%\\gsl.dll       exit 1   # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.gnu.org/software/gsl/
  license: GPL-3.0
  license_file: COPYING
  summary: 'GNU Scientific Library.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
