appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: KQZPe9uHR3HAlwX7WBVP+DkbLySLRsVEk9+6wSGzF3WDfItMazDlnhfkI0cxzSNUxRCemIJSw/lG1635HTzI9KLLLstkxa6hlNjfX8M69nOLUldW+9xWISrFVc941CzPjNz8L/6cLiN+kRio3/DLJW+s7a6O0ML4RYJ1aGlhfX2SkPrS6IVOAV9qoPtk1KV8f3uNLH6RK0GwMJl8nJEQWmRe6lI03uIjumrZxvRcBlRQaB1oJO+AZp+to75gGY6Qqeql9+MUaARz/K5to8lcBy5MekKuGNDNJPeQV0XGjE9ANCy2i6FkT984gJZ3P466eNaqtmoGl7ZChoXS/37r/d81WYJFm/YS9IcTPEUj47uWvdZdDtSo3bN6AuBeXaxssJphPRNQEWOJKj1nTy1GeicpUyoihxjUcap/EEFBhmheoxKFY+3mzuHpIDhaGhzahODv1sw5hUvu8msbqiI1VPX4SNiAN4e3R6W/BsjHCyTncwY2qwS/u0mCFM8w/BhnDieINv/BhRftCli0I87tSsVigri+w9kaVQeFHTzlOTEEwG5OQBwhhzGgDwltNAke/Zdc+6+0abn8iJJo05UQKmQGC6OuCMxXCNPiXPvPiUaMaj77kipwHCd5PdAF4qq+rdk9xdikL4lgIT0TTYL54FMB6nPiHFTCsPufPcbDMR8=}
